# Generated by Django 3.2 on 2024-12-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Admin'), ('usuario', 'Usuario')], default='usuario', max_length=20),
        ),
    ]
