# Generated by Django 3.2 on 2024-12-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPP', '0003_auto_20241208_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
    ]
