# Generated by Django 3.2 on 2024-12-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPP', '0003_auto_20241202_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='habilitada',
            field=models.BooleanField(default=True),
        ),
    ]
