# Generated by Django 3.2 on 2024-12-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPP', '0004_habitacion_habilitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='precio_por_noche',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
